export const NCC_CATALOG = {
  "NIPI": [
    { name: "ATEM Televison - 4K8", unit: "Cái", qty: 1 },
    { name: "ATEM Televison - 8 Input 4K", unit: "Bộ", qty: 1 },
    { name: "Bộ Chủ Naya - 180", unit: "Bộ", qty: 1 },
    { name: "Bộ Intercom Naya", unit: "Bộ", qty: 16 },
    { name: "Bộ Tally Naya", unit: "Bộ", qty: 21 },
    { name: "Tai Nghe Chủ Intercom", unit: "Bộ", qty: 3 },
    { name: "Tai Nghe Intercom", unit: "Bộ", qty: 16 },
    { name: "Đầu Ghi Black - HD", unit: "Đầu", qty: 1 },
    { name: "Đầu Ghi Black - 4K", unit: "Đầu", qty: 1 },
    { name: "Mixer Yamaha", unit: "Bộ", qty: 2 },
    { name: "Tai Nghe Check Audio", unit: "Bộ", qty: 3 },
    { name: "Sony FX6", unit: "Máy", qty: 4 },
    { name: "Sony FX3", unit: "Máy", qty: 10 },
    { name: "Gopro 11 PRO", unit: "Máy", qty: 2 },
    { name: "Hộp Chống Nước Gopro", unit: "Hộp", qty: 10 },
    { name: "Full Grip Tilta FX6", unit: "Bộ", qty: 4 },
    { name: "Tilta Standard Plate", unit: "Bộ", qty: 10 },
    { name: "Tilta 30Cm - Đế + Đũa", unit: "Bộ", qty: 7 },
    { name: "Bộ Đỡ Lens Waraxe", unit: "Đế", qty: 16 },
    { name: "Tay Magic Arm", unit: "Tay", qty: 10 },
    { name: "Lens 16/35 PZ", unit: "Lens", qty: 5 },
    { name: "Lens 16/35 GM1", unit: "Lens", qty: 5 },
    { name: "Lens 28/135 PZ", unit: "Lens", qty: 1 },
    { name: "Lens 24/70 GM", unit: "Lens", qty: 2 },
    { name: "Lens 24/70 GM2", unit: "Lens", qty: 4 },
    { name: "Lens 70/200 GM", unit: "Lens", qty: 6 },
    { name: "Lens 70/200 GM2", unit: "Lens", qty: 4 },
    { name: "Lens 200/600 GM", unit: "Lens", qty: 6 },
    { name: "Lens 400/800 GM", unit: "Lens", qty: 1 },
    { name: "Lens Fix 14 GM", unit: "Lens", qty: 1 },
    { name: "Lens Fix 24 GM", unit: "Filter", qty: 1 },
    { name: "Lens Fix 35 GM", unit: "Filter", qty: 1 },
    { name: "Lens Fix 50 GM", unit: "Filter", qty: 1 },
    { name: "Lens Fix 85 GM", unit: "Filter", qty: 1 },
    { name: "Lens Fix 135 GM", unit: "Filter", qty: 1 },
    { name: "Ring 37 - 82mm", unit: "Filter", qty: 2 },
    { name: "Tele Converter X2 - E-Mount SEL20TC", unit: "Ngàm", qty: 2 },
    { name: "Tay Zoom Bluetooth", unit: "Bộ", qty: 4 },
    { name: "Tay Zoom FX6", unit: "Bộ", qty: 1 },
    { name: "Pin Swit 99", unit: "Pin", qty: 10 },
    { name: "Pin Swit 146", unit: "Pin", qty: 10 },
    { name: "Pin Swit 98", unit: "Pin", qty: 10 },
    { name: "Sạc Pin V-Mount", unit: "Pin", qty: 5 },
    { name: "Pin Tilta FZ100", unit: "Pin", qty: 8 },
    { name: "Sạc Pin Tilta FZ100", unit: "Bộ", qty: 2 },
    { name: "Pin Giả Tilta FZ100", unit: "Pin", qty: 20 },
    { name: "UPS 2K", unit: "Bộ", qty: 2 },
    { name: "Mon Swit - 27''", unit: "Cái", qty: 2 },
    { name: "Mon 7''", unit: "Cái", qty: 2 },
    { name: "Mon Feelword F6", unit: "Cái", qty: 4 },
    { name: "Slider Dolly 2M", unit: "Bộ", qty: 1 },
    { name: "Ronin RS4 Pro", unit: "Bộ", qty: 3 },
    { name: "Ronin RS3 Pro", unit: "Bộ", qty: 1 },
    { name: "Pin Ronin RS3/RS3 Pro/RS4/DJI BG30", unit: "Pin", qty: 3 },
    { name: "Bộ X2 SDI/HDMI 12G", unit: "Bộ", qty: 11 },
    { name: "Bộ SDI/HDMI 12G", unit: "Bộ", qty: 10 },
    { name: "Camlink Swit 500", unit: "Bộ", qty: 4 },
    { name: "Bộ Chia SDI", unit: "Bộ", qty: 1 },
    { name: "Bộ SDI/Optical", unit: "Thẻ", qty: 4 },
    { name: "Thẻ Tough - 160G", unit: "Thẻ", qty: 5 },
    { name: "Thẻ Tough - 128G", unit: "Thẻ", qty: 16 },
    { name: "Thẻ Tough - 80G", unit: "Thẻ", qty: 20 },
    { name: "SSD QVO - 1T", unit: "Thẻ", qty: 1 },
    { name: "SSD EVO - 500G", unit: "Thẻ", qty: 4 },
    { name: "Đầu Chép Tough Sony", unit: "Thẻ", qty: 3 },
    { name: "Đầu Chép SSD", unit: "Thẻ", qty: 3 },
    { name: "SDI - 50m", unit: "Dây", qty: 15 },
    { name: "SDI - 30m", unit: "Dây", qty: 15 },
    { name: "SDI - 20m", unit: "Dây", qty: 15 },
    { name: "SDI - 10m", unit: "Dây", qty: 15 },
    { name: "SDI - Đấu Nối", unit: "Dây", qty: 20 },
    { name: "Cáp Quang - 300m", unit: "Dây", qty: 10 },
    { name: "Cáp Quang Rulo - 1000m", unit: "Dây", qty: 3 },
    { name: "Dây Âm Thanh - 50m", unit: "Dây", qty: 6 },
    { name: "Dây Nguồn FX6", unit: "Dây", qty: 2 },
    { name: "Dây D-Tap", unit: "Dây", qty: 20 },
    { name: "Dây D-Tap FX6", unit: "Dây", qty: 5 },
    { name: "Bộ Nguồn 12V-2A", unit: "Bộ", qty: 20 },
    { name: "Chân Đèn Vàng", unit: "Chân", qty: 10 },
    { name: "Chân Đèn Đen", unit: "Chân", qty: 10 },
    { name: "Chân Đèn Bánh Xe", unit: "Chân", qty: 2 },
    { name: "Tay Arm Đèn", unit: "Chân", qty: 10 }
  ],
  "VĂN HUY": [
    { name: "Sony FX6", unit: "Máy", qty: 6 },
    { name: "Sony FX3", unit: "Máy", qty: 10 },
    { name: "Actioncam 5", unit: "Máy", qty: 5 },
    { name: "Actioncam 6", unit: "Máy", qty: 5 },
    { name: "DJI 360", unit: "Máy", qty: 2 },
    { name: "Tai Nghe Check Audio", unit: "Máy", qty: 3 },
    { name: "Gopro 11 PRO", unit: "Máy", qty: 2 },
    { name: "Hộp Chống Nước Gopro", unit: "Hộp", qty: 2 },
    { name: "Full Grip Tilta FX6", unit: "Bộ", qty: 6 },
    { name: "Tilta Standard Plate", unit: "Bộ", qty: 10 },
    { name: "Tilta 30Cm - Đế + Đũa", unit: "Bộ", qty: 6 },
    { name: "Bộ Đỡ Lens Waraxe", unit: "Đế", qty: 10 },
    { name: "Tay Magic Arm", unit: "Tay", qty: 10 },
    { name: "Lens 16/35 PZ", unit: "Lens", qty: 5 },
    { name: "Lens 16/35 GM", unit: "Lens", qty: 4 },
    { name: "Lens 16/35 GM2", unit: "Lens", qty: 2 },
    { name: "Lens 28/135 PZ", unit: "Lens", qty: 2 },
    { name: "Lens 24/70 GM", unit: "Lens", qty: 4 },
    { name: "Lens 24/70 GM2", unit: "Lens", qty: 3 },
    { name: "Lens 70/200 GM", unit: "Lens", qty: 3 },
    { name: "Lens 70/200 GM2", unit: "Lens", qty: 5 },
    { name: "Lens 200/600 GM", unit: "Lens", qty: 6 },
    { name: "Tay Zoom Bluetooth", unit: "Bộ", qty: 4 },
    { name: "Tay Zoom FX6", unit: "Bộ", qty: 1 },
    { name: "Pin Swit 99", unit: "Pin", qty: 10 },
    { name: "Pin Swit 146", unit: "Pin", qty: 10 },
    { name: "Pin Swit 98", unit: "Pin", qty: 10 },
    { name: "Sạc Pin V-Mount", unit: "Pin", qty: 5 },
    { name: "Pin Tilta FZ100", unit: "Pin", qty: 8 },
    { name: "Sạc Pin Tilta FZ100", unit: "Bộ", qty: 2 },
    { name: "Pin Giả Tilta FZ100", unit: "Pin", qty: 20 },
    { name: "Ronin RS4 Pro", unit: "Bộ", qty: 3 },
    { name: "Ronin RS3 Pro", unit: "Bộ", qty: 1 },
    { name: "Pin Ronin RS3/RS3 Pro/RS4/DJI BG30", unit: "Pin", qty: 3 },
    { name: "Bộ X2 SDI/HDMI 12G", unit: "Bộ", qty: 11 },
    { name: "Bộ SDI/HDMI 12G", unit: "Bộ", qty: 10 },
    { name: "Camlink Swit 500", unit: "Bộ", qty: 4 },
    { name: "Bộ Chia SDI", unit: "Bộ", qty: 1 },
    { name: "Bộ SDI/Optical", unit: "Thẻ", qty: 4 },
    { name: "Thẻ Tough - 160G", unit: "Thẻ", qty: 5 },
    { name: "Thẻ Tough - 128G", unit: "Thẻ", qty: 16 },
    { name: "Thẻ Tough - 80G", unit: "Thẻ", qty: 20 },
    { name: "SSD QVO - 1T", unit: "Thẻ", qty: 1 },
    { name: "SSD EVO - 500G", unit: "Thẻ", qty: 4 },
    { name: "Đầu Chép Tough Sony", unit: "Thẻ", qty: 3 },
    { name: "Đầu Chép SSD", unit: "Thẻ", qty: 3 },
    { name: "SDI - 50m", unit: "Dây", qty: 15 },
    { name: "SDI - 30m", unit: "Dây", qty: 15 },
    { name: "SDI - 20m", unit: "Dây", qty: 15 },
    { name: "SDI - 10m", unit: "Dây", qty: 15 },
    { name: "SDI - Đấu Nối", unit: "Dây", qty: 20 },
    { name: "Cáp Quang - 300m", unit: "Dây", qty: 10 },
    { name: "Cáp Quang Rulo - 1000m", unit: "Dây", qty: 3 },
    { name: "Dây Âm Thanh - 50m", unit: "Dây", qty: 6 },
    { name: "Dây Nguồn FX6", unit: "Dây", qty: 2 },
    { name: "Dây D-Tap", unit: "Dây", qty: 20 },
    { name: "Dây D-Tap FX6", unit: "Dây", qty: 5 }
  ],
  "ZOOM": [
    { name: "ATEM 2 M/E - 20 Input 4K", unit: "Cái", qty: 1 },
    { name: "PANEL 20 - 2 M/E", unit: "Bộ", qty: 1 },
    { name: "Bộ Chủ Naya - 180", unit: "Bộ", qty: 3 },
    { name: "Bộ Intercom Naya", unit: "Bộ", qty: 16 },
    { name: "Bộ Tally Naya", unit: "Bộ", qty: 21 },
    { name: "Tai Nghe Chủ Intercom", unit: "Bộ", qty: 3 },
    { name: "Tai Nghe Intercom", unit: "Bộ", qty: 16 },
    { name: "Đầu Ghi Black - HD", unit: "Đầu", qty: 4 },
    { name: "Đầu Ghi Black - 4K", unit: "Đầu", qty: 4 },
    { name: "Mixer Yamaha", unit: "Bộ", qty: 2 },
    { name: "Tai Nghe Check Audio", unit: "Bộ", qty: 2 },
    { name: "Sony FX6", unit: "Máy", qty: 1 },
    { name: "Sony FX3", unit: "Máy", qty: 40 },
    { name: "Gopro 11 PRO", unit: "Máy", qty: 20 },
    { name: "Actioncam 5", unit: "Máy", qty: 40 },
    { name: "Lens 16/35 PZ", unit: "Lens", qty: 10 },
    { name: "Lens 16/35 GM", unit: "Lens", qty: 5 },
    { name: "Lens 28/135 PZ", unit: "Lens", qty: 4 },
    { name: "Lens 24/70 GM", unit: "Lens", qty: 2 },
    { name: "Lens 24/70 GM2", unit: "Lens", qty: 10 },
    { name: "Lens 70/200 GM", unit: "Lens", qty: 10 },
    { name: "Lens 70/200 GM2", unit: "Lens", qty: 10 },
    { name: "Lens 200/600 GM", unit: "Lens", qty: 10 },
    { name: "Lens 400/800 GM", unit: "Lens", qty: 2 },
    { name: "Ring 37 - 82mm", unit: "Filter", qty: 2 },
    { name: "Tele Converter X2 - E-Mount SEL20TC", unit: "Ngàm", qty: 2 },
    { name: "Tay Zoom Bluetooth", unit: "Bộ", qty: 2 },
    { name: "Tay Zoom FX6", unit: "Bộ", qty: 2 },
    { name: "Pin Swit 99", unit: "Pin", qty: 10 },
    { name: "Pin Swit 146", unit: "Pin", qty: 10 },
    { name: "Pin Swit 98", unit: "Pin", qty: 10 },
    { name: "Sạc Pin V-Mount", unit: "Pin", qty: 10 },
    { name: "Pin Tilta FZ100", unit: "Pin", qty: 20 },
    { name: "Sạc Pin Tilta FZ100", unit: "Bộ", qty: 20 },
    { name: "Pin Giả Tilta FZ100", unit: "Pin", qty: 20 },
    { name: "Mon Bon - 27''", unit: "Cái", qty: 3 },
    { name: "Mon 7''", unit: "Cái", qty: 2 },
    { name: "Mon Feelword F6", unit: "Cái", qty: 4 },
    { name: "Slider Dolly 2M", unit: "Bộ", qty: 1 },
    { name: "Ronin RS4 Pro", unit: "Bộ", qty: 3 },
    { name: "Ronin RS3 Pro", unit: "Bộ", qty: 3 },
    { name: "Pin Ronin RS3/RS3 Pro/RS4/DJI BG30", unit: "Pin", qty: 3 },
    { name: "Bộ X2 SDI/HDMI 12G", unit: "Bộ", qty: 10 },
    { name: "Bộ SDI/HDMI 12G", unit: "Bộ", qty: 10 },
    { name: "DJI Transmission", unit: "Bộ", qty: 2 },
    { name: "DJI SDR", unit: "Bộ", qty: 10 },
    { name: "Camlink SE", unit: "Bộ", qty: 10 },
    { name: "Bộ Chia SDI", unit: "Bộ", qty: 2 },
    { name: "Bộ SDI/Optical", unit: "Thẻ", qty: 10 },
    { name: "Thẻ Tough - 160G", unit: "Thẻ", qty: 5 },
    { name: "Thẻ Tough - 128G", unit: "Thẻ", qty: 20 },
    { name: "Thẻ Tough - 80G", unit: "Thẻ", qty: 20 },
    { name: "SSD QVO - 1T", unit: "Thẻ", qty: 2 },
    { name: "SSD EVO - 500G", unit: "Thẻ", qty: 6 },
    { name: "Đầu Chép Tough Sony", unit: "Thẻ", qty: 3 },
    { name: "Đầu Chép SSD", unit: "Thẻ", qty: 3 },
    { name: "SDI - 50m", unit: "Dây", qty: 15 },
    { name: "SDI - 30m", unit: "Dây", qty: 15 },
    { name: "SDI - 20m", unit: "Dây", qty: 15 },
    { name: "SDI - 10m", unit: "Dây", qty: 15 },
    { name: "SDI - Đấu Nối", unit: "Dây", qty: 20 },
    { name: "Cáp Quang - 300m", unit: "Dây", qty: 10 },
    { name: "Cáp Quang Rulo - 1000m", unit: "Dây", qty: 3 },
    { name: "Dây Âm Thanh - 50m", unit: "Dây", qty: 6 },
    { name: "Dây Nguồn FX6", unit: "Dây", qty: 1 },
    { name: "Dây D-Tap", unit: "Dây", qty: 20 },
    { name: "Dây D-Tap FX6", unit: "Dây", qty: 5 },
    { name: "Bộ Nguồn 12V-2A", unit: "Bộ", qty: 20 },
    { name: "Chân Đèn Vàng", unit: "Chân", qty: 10 },
    { name: "Chân Đèn Đen", unit: "Chân", qty: 10 },
    { name: "Chân Đèn Bánh Xe", unit: "Chân", qty: 2 },
    { name: "Tay Arm Đèn", unit: "Chân", qty: 10 }
  ],
  "A HOÀI": [
    { name: "ATEM Televison - 20 Input HD", unit: "Cái", qty: 1 },
    { name: "PANEL 20 - 2 M/E", unit: "Bộ", qty: 1 },
    { name: "Bộ Chủ Naya - 350", unit: "Bộ", qty: 1 },
    { name: "Bộ Intercom Naya", unit: "Bộ", qty: 10 },
    { name: "Bộ Tally Naya", unit: "Bộ", qty: 10 },
    { name: "Tai Nghe Chủ Intercom", unit: "Bộ", qty: 10 },
    { name: "Tai Nghe Intercom", unit: "Bộ", qty: 10 },
    { name: "Đầu Ghi Black - HD", unit: "Đầu", qty: 5 },
    { name: "Đầu Ghi Black - 4K", unit: "Đầu", qty: 5 },
    { name: "Wide HD - Canon", unit: "Bộ", qty: 2 },
    { name: "Lens X2 - Fujinon", unit: "Bộ", qty: 5 },
    { name: "Lens X2 - Canon", unit: "Máy", qty: 5 },
    { name: "Bộ SDI/HDMI 12G", unit: "Bộ", qty: 10 },
    { name: "Bộ Chia SDI", unit: "Bộ", qty: 5 },
    { name: "Bộ SDI/Optical - Back", unit: "Thẻ", qty: 10 },
    { name: "Bộ SDI/Optical - China", unit: "Thẻ", qty: 10 },
    { name: "Thẻ Tough - 128G", unit: "Thẻ", qty: 20 },
    { name: "Thẻ Tough - 80G", unit: "Thẻ", qty: 20 }
  ],
  "A QUANG": [
    { name: "Wide 4K - Canon", unit: "Cái", qty: 1 },
    { name: "Wide HD - Canon", unit: "Bộ", qty: 3 },
    { name: "Wide HD - Fujinon", unit: "Bộ", qty: 2 },
    { name: "Lens Tele 22X - Fujinon", unit: "Bộ", qty: 3 },
    { name: "Lens Tele 22X - Canon", unit: "Bộ", qty: 4 }
  ],
  "Vinh BĐ": [
    { name: "Bộ Đàm", unit: "Cái", qty: 100 }
  ],
  "A THÁI": [
    { name: "Mixer Live Midas M32", unit: "Bộ", qty: 2 },
    { name: "Mixer Live Alen&Heat SQ7", unit: "Bộ", qty: 1 },
    { name: "Mixer Live Yamaha TF1", unit: "Bộ", qty: 1 },
    { name: "RCF - Sub 9006 AS", unit: "Bộ", qty: 4 },
    { name: "RCF - Full Array HDL 3OA", unit: "Bộ", qty: 16 },
    { name: "RCF - Monitor ST12 SMA", unit: "Bộ", qty: 8 },
    { name: "JBL - Sub", unit: "Bộ", qty: 6 },
    { name: "JBL - Full", unit: "Bộ", qty: 6 },
    { name: "JBL - Monitor", unit: "Bộ", qty: 10 },
    { name: "Main U2 - 4 Kênh", unit: "Bộ", qty: 5 },
    { name: "Main U2 - 2 Kênh", unit: "Bộ", qty: 5 },
    { name: "Main CA20", unit: "Bộ", qty: 2 },
    { name: "Monitor Yamaha", unit: "Bộ", qty: 2 },
    { name: "Monitor Behringer", unit: "Bộ", qty: 2 },
    { name: "Headphone - Âm Thanh", unit: "Bộ", qty: 5 },
    { name: "Micro Cầm Tay Sennheiser G3", unit: "Bộ", qty: 17 },
    { name: "Micro Sennheiser G3 - Body Điện", unit: "Bộ", qty: 15 },
    { name: "Micro Sennheiser G3 - Body Pin", unit: "Bộ", qty: 9 },
    { name: "Micro Cầm Tay Shure UR", unit: "Bộ", qty: 2 },
    { name: "Bộ Receiver Sennheiser G3", unit: "Bộ", qty: 27 },
    { name: "Shure SM57", unit: "Bộ", qty: 5 },
    { name: "Shure SM58", unit: "Bộ", qty: 3 },
    { name: "Shure SM81", unit: "Bộ", qty: 2 },
    { name: "Shure Beta52", unit: "Bộ", qty: 1 },
    { name: "Shure Beta91", unit: "Bộ", qty: 1 },
    { name: "Shure DPA", unit: "Bộ", qty: 10 },
    { name: "Micro Ken Audio Technica", unit: "Bộ", qty: 1 },
    { name: "Micro Headset - China", unit: "Bộ", qty: 35 },
    { name: "Micro Headset - China Ngày 21/04/26", unit: "Bộ", qty: 40 },
    { name: "Micro Cổ Nghổng - China", unit: "Bộ", qty: 7 },
    { name: "Micro Cài Áo - Sennheiser", unit: "Bộ", qty: 18 },
    { name: "Micro Rode NTG2", unit: "Bộ", qty: 1 },
    { name: "Micro Shotgun - Boya-BM6060", unit: "Bộ", qty: 25 },
    { name: "Micro Shotgun - Synco D1", unit: "Bộ", qty: 11 },
    { name: "Bộ Inear Sennheiser", unit: "Bộ", qty: 1 },
    { name: "Bộ Mono DI-Box", unit: "Bộ", qty: 4 },
    { name: "Bộ Stereo DI-Box", unit: "Bộ", qty: 3 },
    { name: "Bộ Recorder Zoom F8", unit: "Bộ", qty: 1 },
    { name: "Bộ Recorder Zoom H6", unit: "Bộ", qty: 1 },
    { name: "Box Midas 16", unit: "Bộ", qty: 2 },
    { name: "Box Chia Tín Hiệu", unit: "Bộ", qty: 1 },
    { name: "Bộ XLR To Optical - 2in/2out", unit: "Bộ", qty: 18 },
    { name: "Bộ XLR To Optical - 4in/4out", unit: "Bộ", qty: 2 },
    { name: "Bộ XLR To Optical - 8in/8out", unit: "Bộ", qty: 11 },
    { name: "Tai Nghe Kiểm Âm + Jack 6mm To XLR", unit: "Bộ", qty: 20 },
    { name: "Bộ Shure MC - Sony", unit: "Bộ", qty: 3 },
    { name: "Cross Xilica XP 4080", unit: "Bộ", qty: 1 },
    { name: "Cross Admax", unit: "Bộ", qty: 1 },
    { name: "Coross Asly", unit: "Bộ", qty: 1 },
    { name: "Bộ Lá Sóng Sennheiser", unit: "Bộ", qty: 2 },
    { name: "Wireless Boom - Sennheiser", unit: "Bộ", qty: 1 },
    { name: "Rdnet Control", unit: "Bộ", qty: 1 },
    { name: "Lông Thú Chắn Gió", unit: "Bộ", qty: 11 },
    { name: "Bộ Đàm Motorola - Âm Thanh", unit: "Bộ", qty: 6 },
    { name: "Balang Treo Loa", unit: "Bộ", qty: 1 },
    { name: "Giá Treo Loa - RCF", unit: "Bộ", qty: 1 },
    { name: "Dây Tín Hiệu Canon", unit: "Sợi", qty: 1 },
    { name: "Dây Mạng CAT6", unit: "Sợi", qty: 1 },
    { name: "Dây Nguồn Điện - Âm Thanh", unit: "Sợi", qty: 1 },
    { name: "Tủ Điện 100A - Âm Thanh", unit: "Tủ", qty: 1 },
    { name: "Chân Loa", unit: "Chân", qty: 12 },
    { name: "Chân Organ", unit: "Chân", qty: 3 },
    { name: "Chân Guitar", unit: "Chân", qty: 3 },
    { name: "Chân Mic - Tam Giác", unit: "Chân", qty: 10 },
    { name: "Chân Mic - Tròn", unit: "Chân", qty: 11 },
    { name: "Chân Mic - Để BànTranshine HY-332", unit: "Chân", qty: 40 },
    { name: "Imax 27''", unit: "Máy", qty: 1 },
    { name: "Mac Pro 15''", unit: "Máy", qty: 2 },
    { name: "Mac Pro 13''", unit: "Máy", qty: 1 },
    { name: "Mac Air 13''", unit: "Máy", qty: 1 },
    { name: "HDD", unit: "HDD", qty: 2 },
    { name: "Trạm Điện Di Động", unit: "Bộ", qty: 3 },
    { name: "Ổ Cắm Điện 10 Lỗ", unit: "Ổ", qty: 2 },
    { name: "Ổ Cắm Điện 6 Lỗ", unit: "Ổ", qty: 8 },
    { name: "Bộ Sạc Pin AA", unit: "Bộ", qty: 2 },
    { name: "Bộ Sạc Pin AA - Nhỏ", unit: "Bộ", qty: 3 },
    { name: "Pin AA", unit: "Pin", qty: 100 },
    { name: "UPS 1K - Âm Thanh", unit: "UPS", qty: 2 }
  ],
  "A HIỆP": [
    { name: "Mixer MA 2 SCREEN", unit: "Bộ", qty: 1 },
    { name: "Mixer Tiger Touch", unit: "Bộ", qty: 6 },
    { name: "Mixer Pear 2010", unit: "Bộ", qty: 1 },
    { name: "Đèn Spot PR - 1000w", unit: "Bộ", qty: 12 },
    { name: "Đèn Spot LED - 400w", unit: "Bộ", qty: 20 },
    { name: "Đèn BigEye", unit: "Bộ", qty: 20 },
    { name: "Đèn Katana - 1M", unit: "Bộ", qty: 30 },
    { name: "Đèn Katana - 50CM", unit: "Bộ", qty: 20 },
    { name: "Đèn Beam 260", unit: "Bộ", qty: 100 },
    { name: "Đèn Beam 230", unit: "Bộ", qty: 21 },
    { name: "Đèn Beam 190 - LED", unit: "Bộ", qty: 40 },
    { name: "Đèn Parled 2in1 - 3K2 + 5K6", unit: "Bộ", qty: 20 },
    { name: "Đèn Parled BK - Outdoor", unit: "Bộ", qty: 99 },
    { name: "Đèn Parled - Indoor", unit: "Bộ", qty: 57 },
    { name: "Đèn Cyclorama LED", unit: "Bộ", qty: 20 },
    { name: "Đèn Fresnel 200W - LED", unit: "Bộ", qty: 20 },
    { name: "Đèn Fresnel 2000W - Xanh", unit: "Bộ", qty: 97 },
    { name: "Đèn Led COB 200W", unit: "Bộ", qty: 62 },
    { name: "Đèn Blinder 750W", unit: "Bộ", qty: 85 },
    { name: "Đèn Par 64 - 1000W", unit: "Bộ", qty: 70 },
    { name: "Đèn Profile 2000W", unit: "Bộ", qty: 15 },
    { name: "Đèn Profile 750W", unit: "Bộ", qty: 13 },
    { name: "Đèn Profile 2000W - LED", unit: "Bộ", qty: 6 },
    { name: "Đèn Profile 300W - LED", unit: "Bộ", qty: 10 },
    { name: "Đèn Follow DTS - 1500W", unit: "Bộ", qty: 1 },
    { name: "Đèn Laser 5W", unit: "Bộ", qty: 2 },
    { name: "Máy Haze Z500", unit: "Bộ", qty: 5 },
    { name: "Máy Haze Z6500", unit: "Bộ", qty: 2 },
    { name: "Máy Khói Z3000W", unit: "Bộ", qty: 2 },
    { name: "Tăng Cường Tín Hiệu Ánh Sáng", unit: "Bộ", qty: 18 },
    { name: "CS Dimmer Pack - 12CB", unit: "Bộ", qty: 48 },
    { name: "Bộ Art Net - 16 Out", unit: "Bộ", qty: 6 },
    { name: "Khung Truss Nhôm - 400x400", unit: "Mét", qty: 60 },
    { name: "Khung Truss Nhôm - Tròn 4m2", unit: "Bộ", qty: 1 },
    { name: "Khung Truss Sắt - 400x400", unit: "Mét", qty: 500 },
    { name: "Khung Truss Sắt - Tròn 6m", unit: "Bộ", qty: 1 },
    { name: "Khung Truss Sắt - Tròn 2m", unit: "Bộ", qty: 1 },
    { name: "Tuýp Đèn Beam", unit: "Cây", qty: 20 },
    { name: "Cùm Đèn", unit: "Cùm", qty: 200 },
    { name: "Palang - 2T", unit: "Bộ", qty: 100 },
    { name: "Dây Bẹ - 5T", unit: "Bộ", qty: 50 },
    { name: "Chân Chỏi Truss", unit: "Chân", qty: 35 },
    { name: "Tủ Điện 250A", unit: "Bộ", qty: 1 },
    { name: "Dây Điện - 3 Pha", unit: "Mét", qty: 50 },
    { name: "Dây Điện - 16 Lõi", unit: "Dây", qty: 50 },
    { name: "Dây Điện - Đấu Nối", unit: "Dây", qty: 200 },
    { name: "Dây Tín Hiệu Dài - Ánh Sáng", unit: "Dây", qty: 50 },
    { name: "Dây Tín Hiệu Ngắn - Ánh Sáng", unit: "Dây", qty: 50 },
    { name: "Tấm Palet Nhựa", unit: "Tấm", qty: 50 }
  ],
  "A TÌNH": [
    { name: "Aputure 1200D", unit: "Bộ", qty: 1 },
    { name: "Aputure 600C", unit: "Bộ", qty: 6 },
    { name: "Aputure 600X", unit: "Bộ", qty: 1 },
    { name: "Aputure 300X", unit: "Bộ", qty: 1 },
    { name: "Nova 300C", unit: "Bộ", qty: 12 },
    { name: "Nova 300X", unit: "Bộ", qty: 20 },
    { name: "Nova 200C", unit: "Bộ", qty: 20 },
    { name: "Nova 200X", unit: "Bộ", qty: 30 },
    { name: "Led Wasa T2C", unit: "Bộ", qty: 100 },
    { name: "Led Wasa T4C", unit: "Bộ", qty: 21 },
    { name: "Nanlite 500W", unit: "Bộ", qty: 40 },
    { name: "Nanlite 200W", unit: "Bộ", qty: 20 },
    { name: "Dolly Kaypo", unit: "Bộ", qty: 57 },
    { name: "Amaran F22C", unit: "Bộ", qty: 20 },
    { name: "Amaran F21C", unit: "Bộ", qty: 97 },
    { name: "Amaran PT4C", unit: "Bộ", qty: 20 },
    { name: "Amaran 600C", unit: "Bộ", qty: 20 },
    { name: "Amaran 300C", unit: "Bộ", qty: 20 }
  ],
  "ALTA": [
    { name: "LED P3.91 - Indoor - Cabin 500x500", unit: "Cabin", qty: 500 },
    { name: "Magnimage - MH570", unit: "Bộ", qty: 2 },
    { name: "Cardsen Nova  MCTRL600", unit: "Bộ", qty: 6 },
    { name: "Bộ PC + Card SDI + Màn Hình PC", unit: "Bộ", qty: 1 },
    { name: "Dây DVI - LED", unit: "Dây", qty: 4 },
    { name: "Dây Mạng CAT6 - 50M", unit: "Dây", qty: 16 },
    { name: "Dây Tín Hiệu Line - RJ45", unit: "Dây", qty: 100 },
    { name: "Dây Nguồn Line - LED", unit: "Dây", qty: 100 },
    { name: "Dây Nguồn 16A - LED", unit: "Dây", qty: 27 },
    { name: "Hộp Điện 20A - LED", unit: "Hộp", qty: 3 },
    { name: "Dây Điện - 3 Pha 63A", unit: "Dây", qty: 3 },
    { name: "Tay Chỏi LED", unit: "Tay", qty: 33 },
    { name: "Tuýt Sắt LED", unit: "Tuýt", qty: 12 },
    { name: "Đế Sắt LED - 20cmx30cm", unit: "Đế", qty: 30 },
    { name: "Đà LED - Sắt Hộp", unit: "Cây", qty: 7 }
  ],
  "DMX": [
    { name: "Matrix Led - Thanh 1M", unit: "Thanh", qty: 320 },
    { name: "Matrix Led - Dây", unit: "Mét", qty: 350 },
    { name: "Matrix Led - Tube 1M", unit: "Thanh", qty: 50 },
    { name: "Matrix Led - Vuông 60x60", unit: "Bộ", qty: 15 },
    { name: "Key 3 - Control Matrix", unit: "Cái", qty: 1 },
    { name: "Nguồn 12V - Matrix Led", unit: "Bộ", qty: 46 },
    { name: "Laptop MSI", unit: "Bộ", qty: 1 },
    { name: "Laptop Alienware", unit: "Bộ", qty: 1 },
    { name: "Dây Mạng CAT6", unit: "Dây", qty: 10 },
    { name: "Dây Nguồn Điện", unit: "Dây", qty: 10 },
    { name: "Tủ Điện 100A", unit: "Bộ", qty: 1 }
  ],
  "SK OUT": [
    { name: "Kính Cường Lực 12mm", unit: "Tấm", qty: 169 },
    { name: "Kính Cường Lực 10mm", unit: "Tấm", qty: 55 },
    { name: "Ván Outdoor 17mm", unit: "Tấm", qty: 40 },
    { name: "Ván MDF", unit: "Tấm", qty: 210 },
    { name: "Sàn Kính 12mm - 6M", unit: "Sàn", qty: 1 },
    { name: "Sàn Kính 12mm - 3,6M", unit: "Sàn", qty: 1 },
    { name: "Sắt Hộp 4x8", unit: "Cây", qty: 130 },
    { name: "Thanh Đứng 1M - Đen", unit: "Cây", qty: 36 },
    { name: "Thanh Đứng 1M - Trắng", unit: "Cây", qty: 99 },
    { name: "Thanh Đứng 2M - Đen", unit: "Cây", qty: 168 },
    { name: "Thanh Đứng 2M - Trắng", unit: "Cây", qty: 275 },
    { name: "Thanh Chéo Dài - Đen", unit: "Cây", qty: 197 },
    { name: "Thanh Chéo Dài - Trắng", unit: "Cây", qty: 350 },
    { name: "Thanh Chéo Ngắn - Đen", unit: "Cây", qty: 24 },
    { name: "Thanh Ngang 2M - Đen", unit: "Cây", qty: 549 },
    { name: "Thanh Ngang 2M - Trắng", unit: "Cây", qty: 588 },
    { name: "Thanh Ngang 1M - Đen", unit: "Cây", qty: 36 },
    { name: "Chân Kích", unit: "Chân", qty: 71 },
    { name: "Mâm Layer - Lớn", unit: "Mâm", qty: 10 },
    { name: "Mâm Layer - Nhỏ", unit: "Mâm", qty: 25 },
    { name: "Cầu Thang - Layer", unit: "Mâm", qty: 12 }
  ]
};

export const NCC_LIST = Object.keys(NCC_CATALOG);

export const NCC_DEPT = {
  'NIPI':    ['TECH'],
  'VĂN HUY': ['TECH'],
  'ZOOM':    ['TECH'],
  'A HOÀI':  ['TECH'],
  'A QUANG': ['TECH'],
  'Vinh BĐ': ['TECH'],
  'A THÁI':  ['ATAS'],
  'A HIỆP':  ['ATAS'],
  'A TÌNH':  ['ATAS'],
  'ALTA':    ['ATAS'],
  'DMX':     ['ATAS'],
  'SK OUT':  ['STAGE'],
};