export const NCC_CATALOG = {
  "NIPI": [
    { name: "ATEM 20 Input - 2 M/E Constellation 4K", unit: "Cái" },
    { name: "ATEM 40 Input - 4 M/E Constellation 4K", unit: "Cái" },
    { name: "ATEM 20 Input - Televison Studio HD", unit: "Cái" },
    { name: "ATEM Televison Studio - 4K", unit: "Bộ" },
    { name: "PANEL 30 Input - 4 M/E", unit: "Cái" },
    { name: "PANEL 20 Input - 2 M/E", unit: "Cái" },
    { name: "Datavideo SE-2800 + Control Panel", unit: "Bộ" },
    { name: "Datavideo SE-3000 + Control Panel", unit: "Bộ" },
    { name: "Datavideo SE-3200 + Control Panel", unit: "Bộ" },
    { name: "Datavideo HS-2800", unit: "Bộ" },
    { name: "Datavideo HS-2000L", unit: "Bộ" },
    { name: "Datavideo HS-400", unit: "Bộ" },
    { name: "Bộ Chủ Intercom Naya - 360", unit: "Bộ" },
    { name: "Bộ Chủ Intercom Naya - 180", unit: "Bộ" },
    { name: "Bộ Intercom Wireless Naya", unit: "Bộ" },
    { name: "Bộ Tally Wireless Naya", unit: "Bộ" },
    { name: "Tai Nghe Chủ Intercom", unit: "Bộ" },
    { name: "Tai Nghe Intercom", unit: "Bộ" },
    { name: "Đầu Ghi Blackmagic - Analog", unit: "Đầu" },
    { name: "Đầu Ghi Blackmagic - 4K", unit: "Đầu" },
    { name: "Bộ Teranex Mini Auido 12G", unit: "Bộ" },
    { name: "Bộ Chống Nhiễu Âm Thanh", unit: "Bộ" },
    { name: "Thanh Rack SDI", unit: "Thanh" },
    { name: "Audio Monitor BX8", unit: "Cái" },
    { name: "Bộ Đàm + Tai Nghe", unit: "Bộ" },
    { name: "Sạc Bộ Đàm", unit: "Bộ" },
    { name: "Datavideo ITC-100 + Mic", unit: "Bộ" },
    { name: "Bộ Beltpack Datavideo ITC-100L", unit: "Bộ" },
    { name: "Đèn Tally Datavideo", unit: "Bộ" },
    { name: "Datavideo Card-SDI", unit: "Bộ" },
    { name: "Sony PXW-X400", unit: "Máy" },
    { name: "Sony PMW-350", unit: "Máy" },
    { name: "Panasonic P2-2100", unit: "Máy" },
    { name: "Panasonic P2-800", unit: "Máy" },
    { name: "Panasonic P2-600", unit: "Máy" },
    { name: "Panasonic P2-500", unit: "Máy" },
    { name: "Panasonic P2-370", unit: "Máy" },
    { name: "Panasonic P2-302", unit: "Máy" },
    { name: "Panasonic P2-250", unit: "Máy" },
    { name: "Camera JVC", unit: "Máy" },
    { name: "Sony FX6", unit: "Máy" },
    { name: "Sony FX3", unit: "Máy" },
    { name: "Sony FR7", unit: "Máy" },
    { name: "Control FR7 - RM-IP500/3 SY", unit: "Bộ" },
    { name: "Gopro Hero 11 PRO", unit: "Máy" },
    { name: "Hộp Chống Nước Gopro", unit: "Hộp" },
    { name: "Canon 5D Mark II", unit: "Máy" },
    { name: "Minicam HD", unit: "Máy" },
    { name: "Handycam Sony - 4K", unit: "Máy" },
    { name: "Handycam Sony - HD - CX405", unit: "Máy" },
    { name: "Full Grip Tilta FX6", unit: "Bộ" },
    { name: "Tilta FX3 + Kẹp HDMI", unit: "Bộ" },
    { name: "Top Handheld Tilta", unit: "Bộ" },
    { name: "Tilta V-Mount", unit: "Bộ" },
    { name: "Tilta Standard Plate", unit: "Bộ" },
    { name: "Tilta 30Cm - Đế + Đũa", unit: "Bộ" },
    { name: "Girp FR7 - Topshot", unit: "Bộ" },
    { name: "Bộ Đế Pin Ronin", unit: "Đế" },
    { name: "Bộ Đỡ Lens Waraxe", unit: "Đế" },
    { name: "Tay Magic Arm", unit: "Tay" },
    { name: "Lens Wide Canon - 4K", unit: "Lens" },
    { name: "Lens Wide Canon - HD", unit: "Lens" },
    { name: "Lens Wide Fujinon - HD", unit: "Lens" },
    { name: "Lens Supper Tele Canon 40X", unit: "Lens" },
    { name: "Lens Supper Tele Fujinon 42X", unit: "Lens" },
    { name: "Lens KIT - Fujinon", unit: "Lens" },
    { name: "Lens KIT - Canon", unit: "Lens" },
    { name: "Lens X2 - Fujinon", unit: "Lens" },
    { name: "Lens X2 - Canon", unit: "Lens" },
    { name: "Lens Canon Cine 17/120", unit: "Lens" },
    { name: "Lens Canon EF-16/35", unit: "Lens" },
    { name: "Lens Canon EF-17/40", unit: "Lens" },
    { name: "Lens Canon EF-24/70", unit: "Lens" },
    { name: "Lens Canon EF-24/105", unit: "Lens" },
    { name: "Lens Canon EF-70/200", unit: "Lens" },
    { name: "Lens Canon Cine Fix 24mm", unit: "Lens" },
    { name: "Lens Canon Cine Fix 50mm", unit: "Lens" },
    { name: "Lens Canon Cine Fix 85mm", unit: "Lens" },
    { name: "Lens Canon Fix 50mm", unit: "Lens" },
    { name: "Lens Sony 16/35 PZ", unit: "Lens" },
    { name: "Lens Sony 16/35 GM1", unit: "Lens" },
    { name: "Lens Sony 16/35 GM2", unit: "Lens" },
    { name: "Lens Sony 28/135 PZ", unit: "Lens" },
    { name: "Lens Sony 24/70 GM", unit: "Lens" },
    { name: "Lens Sony 70/200 GM", unit: "Lens" },
    { name: "Lens Sony 70/200 GM2", unit: "Lens" },
    { name: "Lens Sony 200/600 GM", unit: "Lens" },
    { name: "Lens Sony 400/800 GM", unit: "Lens" },
    { name: "Lens Laowa 10mm", unit: "Lens" },
    { name: "Filter Hoya 77mm", unit: "Filter" },
    { name: "Filter Soulmate UV95mm", unit: "Filter" },
    { name: "Filter UV 95mm", unit: "Filter" },
    { name: "Filter Tiffen 82mm", unit: "Filter" },
    { name: "Filter 37mm To 82mm", unit: "Filter" },
    { name: "M43 Mount", unit: "Ngàm" },
    { name: "EF To B4 Mount", unit: "Ngàm" },
    { name: "Tele Converter X2 - E-Mount SEL20TC", unit: "Ngàm" },
    { name: "Tay Zoom Canon B4", unit: "Bộ" },
    { name: "Tay Focus Canon B4", unit: "Bộ" },
    { name: "Tay Zoom Fujinon B4", unit: "Bộ" },
    { name: "Tay Focus Fujinon B4", unit: "Bộ" },
    { name: "Tay Zoom 9EX", unit: "Bộ" },
    { name: "Tay Zoom Bluetooth - Sony", unit: "Bộ" },
    { name: "Tay Zoom FX3", unit: "Bộ" },
    { name: "Tay Zoom Handheld FX6", unit: "Bộ" },
    { name: "Tay Zoom Libec ZFC-L", unit: "Bộ" },
    { name: "Pin Swit 99 - V-Mount", unit: "Pin" },
    { name: "Pin Swit 146 - V-Mount", unit: "Pin" },
    { name: "Pin Swit 98 - V-Mount", unit: "Pin" },
    { name: "Sạc Pin V-Mount", unit: "Pin" },
    { name: "Pin Tilta FZ102", unit: "Pin" },
    { name: "Sạc Pin Tilta FZ102", unit: "Bộ" },
    { name: "Pin Giả Tilta FZ102", unit: "Pin" },
    { name: "Pin V-Mount", unit: "Pin" },
    { name: "Pin G-Mount", unit: "Pin" },
    { name: "Pin V-BP360", unit: "Pin" },
    { name: "Sạc Pin G-Mount", unit: "Bộ" },
    { name: "UPS 2K - New", unit: "Bộ" },
    { name: "UPS 2K", unit: "Bộ" },
    { name: "Bộ Quản Lý Nguồn", unit: "Bộ" },
    { name: "Trạm Điện Di Động", unit: "Bộ" },
    { name: "Pin Dự Phòng", unit: "Bộ" },
    { name: "Bộ PC", unit: "Bộ" },
    { name: "Card SDI Blackmagic", unit: "Bộ" },
    { name: "Màn Hình 17''", unit: "Bộ" },
    { name: "Monitor Swit - 27''", unit: "Cái" },
    { name: "Monitor Bon - 14''", unit: "Cái" },
    { name: "Monitor Panasonic - 14''", unit: "Cái" },
    { name: "Monitor Datavideo - 17''", unit: "Cái" },
    { name: "Monitor Blackmagic - 17''", unit: "Cái" },
    { name: "Monitor Blackmagic Đôi - 9''", unit: "Cái" },
    { name: "Monitor Feelword F6 Plus", unit: "Cái" },
    { name: "Monitor Seetec 15''", unit: "Cái" },
    { name: "TV Sony 65'", unit: "Cái" },
    { name: "TV Sony 55'", unit: "Cái" },
    { name: "TV Redmi 43''", unit: "Cái" },
    { name: "TV Sony 42''", unit: "Cái" },
    { name: "TV Asanzo 40''", unit: "Cái" },
    { name: "Bộ Vazizoom + Zoom, Forcus, Iris", unit: "Bộ" },
    { name: "Boom 12m", unit: "Bộ" },
    { name: "Boom 8m", unit: "Cái" },
    { name: "Thanh Dolly - Thẳng 2M", unit: "Thanh" },
    { name: "Thanh Dolly - Cong 2M", unit: "Thanh" },
    { name: "Mâm Dolly", unit: "Mâm" },
    { name: "Bánh Xe Dolly", unit: "Bánh" },
    { name: "Slider Dolly 2M", unit: "Bộ" },
    { name: "Pin Ronin RS3/RS3 Pro/RS4/DJI BG30", unit: "Pin" },
    { name: "Steadicam G45", unit: "Bộ" },
    { name: "Chân E-image", unit: "Chân" },
    { name: "Chân Vinten Trắng", unit: "Chân" },
    { name: "Chân SC", unit: "Chân" },
    { name: "Chân Baby", unit: "Chân" },
    { name: "Chân Sachtler", unit: "Chân" },
    { name: "Chân Secced V15", unit: "Chân" },
    { name: "DJI Transmission - Wireless Video", unit: "Bộ" },
    { name: "Bộ Converter SDI/HDMI 12G", unit: "Bộ" },
    { name: "Bộ Chia SDI - Bon", unit: "Bộ" },
    { name: "Bộ Chia HDMI", unit: "Bộ" },
    { name: "Bộ SDI To Optical - Backmagic", unit: "Bộ" },
    { name: "Bộ SDI To Optical - China", unit: "Bộ" },
    { name: "Bộ Teranex 2D + Dây 25 Pin", unit: "Bộ" },
    { name: "Thẻ Tough Sony - 160G", unit: "Thẻ" },
    { name: "Thẻ Tough Sony - 80G", unit: "Thẻ" },
    { name: "Thẻ CF Homan - 256G", unit: "Thẻ" },
    { name: "Thẻ CF - 16G", unit: "Thẻ" },
    { name: "Thẻ CF - 32G", unit: "Thẻ" },
    { name: "Thẻ SXS - 128G", unit: "Thẻ" },
    { name: "Thẻ SXS - 64G - New", unit: "Thẻ" },
    { name: "Thẻ SXS - 64G", unit: "Thẻ" },
    { name: "Thẻ SXS - 32G", unit: "Thẻ" },
    { name: "Thẻ SXS - 16G", unit: "Thẻ" },
    { name: "Thẻ SXS - 8G", unit: "Thẻ" },
    { name: "Thẻ P2 - 64G", unit: "Thẻ" },
    { name: "Thẻ P2 - 32G", unit: "Thẻ" },
    { name: "Thẻ P2 - 26G", unit: "Thẻ" },
    { name: "Thẻ Micro SD - Sandisk 128G", unit: "Thẻ" },
    { name: "Thẻ SD - Sandisk 512G", unit: "Thẻ" },
    { name: "Thẻ SD - Sandisk 256G", unit: "Thẻ" },
    { name: "HDD 4TB USB 3.0", unit: "Bộ" },
    { name: "HDD 6TB USB 3.0", unit: "Cái" },
    { name: "HDD 8TB USB 3.0", unit: "Cái" },
    { name: "SSD Samsung - 500G - T7 Xanh", unit: "Cái" },
    { name: "SSD Samsung - 1T", unit: "Cái" },
    { name: "SSD Samsung - 500G", unit: "Cái" },
    { name: "SSD Samsung - 250G", unit: "Cái" },
    { name: "Đầu Chép Thẻ Tough Sony", unit: "Cái" },
    { name: "Đầu Chép Thẻ CF Homan", unit: "Cái" },
    { name: "Đầu Chép Thẻ CF", unit: "Cái" },
    { name: "Đầu Chép SSD", unit: "Cái" },
    { name: "Đầu Chép SXS Sony 3.0", unit: "Cái" },
    { name: "Đầu Chép SXS Sony 2.0", unit: "Cái" },
    { name: "Đầu Chép Panasonic 3.0", unit: "Cái" },
    { name: "Đầu Chép Panasonic 2.0", unit: "Cái" },
    { name: "Dây SDI 5.5 - 80m", unit: "Dây" },
    { name: "Dây SDI 4.5 - 80m", unit: "Dây" },
    { name: "Dây SDI 4.5 - 50m", unit: "Dây" },
    { name: "Dây SDI 4.5 - 20m", unit: "Dây" },
    { name: "Dây SDI 4.5 - 10m", unit: "Dây" },
    { name: "Dây SDI China - 100m", unit: "Dây" },
    { name: "Dây SDI China - 50m", unit: "Dây" },
    { name: "Dây SDI China - 20m", unit: "Dây" },
    { name: "Dây SDI China - 10m", unit: "Dây" },
    { name: "Dây Cáp Quang - 300m", unit: "Dây" },
    { name: "Dây Âm Thanh - 50m", unit: "Dây" },
    { name: "Dây Nguồn Camera - 50m", unit: "Dây" },
    { name: "Dây Nguồn FX6", unit: "Dây" },
    { name: "Dây D-Tap", unit: "Dây" },
    { name: "Dây D-Tap FX6", unit: "Dây" },
    { name: "Dây Type-C", unit: "Dây" },
    { name: "Dây Tín Hiệu Boom", unit: "Bộ" },
    { name: "Dây HDMI - 30M", unit: "Dây" },
    { name: "Đầu DVI To HDMI", unit: "Đầu" },
    { name: "Đầu DP To HDMI", unit: "Đầu" },
    { name: "Bộ Adaptor 12V-2A", unit: "Bộ" },
    { name: "Bộ Hub Nguồn -  100 USB", unit: "Bộ" },
    { name: "Bộ Nguồn PD-1", unit: "Bộ" },
    { name: "Bộ Nguồn PD-2", unit: "Bộ" },
    { name: "Bộ Nguồn PD-3", unit: "Bộ" },
    { name: "Chân Đèn Sixten", unit: "Chân" },
    { name: "Chân Đèn Vàng", unit: "Chân" },
    { name: "Chân Đèn W", unit: "Chân" },
    { name: "Chân Đèn Đen", unit: "Chân" },
    { name: "Chân Đèn Bánh Xe", unit: "Chân" },
    { name: "Tay Arm Đèn", unit: "Arm" },
    { name: "Thùng PANEL 30 Input - 4 M/E", unit: "Thùng" },
    { name: "Thùng PANEL 20 Input - 2 M/E", unit: "Thùng" },
    { name: "Thùng Monitor Swit 27''", unit: "Thùng" },
    { name: "Túi Đựng Tivi 43''", unit: "Túi" },
    { name: "Hộp Đựng Monitor Seteec", unit: "Hộp" },
    { name: "Thùng Nhựa 55L", unit: "Thùng" },
    { name: "Thùng Nhựa 30L", unit: "Thùng" },
    { name: "Bao Cát", unit: "Bao" },
    { name: "Pallet Nhựa", unit: "Tấm" },
    { name: "Thùng Mixer Âm Thanh", unit: "Thùng" },
    { name: "Thanh Quạt Tản Nhiệt 2U", unit: "Thanh" },
    { name: "Thanh Quạt Tản Nhiệt 4U", unit: "Thanh" },
    { name: "Dù Cầm Tay", unit: "Dù" },
    { name: "Máy Quạt", unit: "Cái" },
    { name: "Xe Đẩy - Đỏ", unit: "Xe" },
    { name: "Balo Baroca Lenser", unit: "Balo" },
    { name: "Túi Dụng Cụ Boom", unit: "Túi" },
  ],
  "LONG PATE": [
    { name: "Mixer Live Midas M32", unit: "Bộ" },
    { name: "Mixer Live Alen&Heat SQ7", unit: "Bộ" },
    { name: "Mixer Live Yamaha TF1", unit: "Bộ" },
    { name: "RCF - Sub 9006 AS", unit: "Bộ" },
    { name: "RCF - Full Array HDL 3OA", unit: "Bộ" },
    { name: "RCF - Monitor ST12 SMA", unit: "Bộ" },
    { name: "JBL - Sub", unit: "Bộ" },
    { name: "JBL - Full", unit: "Bộ" },
    { name: "JBL - Monitor", unit: "Bộ" },
    { name: "Main U2 - 4 Kênh", unit: "Bộ" },
    { name: "Main U2 - 2 Kênh", unit: "Bộ" },
    { name: "Main CA20", unit: "Bộ" },
    { name: "Monitor Yamaha", unit: "Bộ" },
    { name: "Monitor Behringer", unit: "Bộ" },
    { name: "Headphone - Âm Thanh", unit: "Bộ" },
    { name: "Micro Cầm Tay Sennheiser G3", unit: "Bộ" },
    { name: "Micro Sennheiser G3 - Body Điện", unit: "Bộ" },
    { name: "Micro Sennheiser G3 - Body Pin", unit: "Bộ" },
    { name: "Micro Cầm Tay Shure UR", unit: "Bộ" },
    { name: "Bộ Receiver Sennheiser G3", unit: "Bộ" },
    { name: "Shure SM57", unit: "Bộ" },
    { name: "Shure SM58", unit: "Bộ" },
    { name: "Shure SM81", unit: "Bộ" },
    { name: "Shure Beta52", unit: "Bộ" },
    { name: "Shure Beta91", unit: "Bộ" },
    { name: "Shure DPA", unit: "Bộ" },
    { name: "Micro Ken Audio Technica", unit: "Bộ" },
    { name: "Micro Headset - China", unit: "Bộ" },
    { name: "Micro Headset - China Ngày 21/04/26", unit: "Bộ" },
    { name: "Micro Cổ Nghổng - China", unit: "Bộ" },
    { name: "Micro Cài Áo - Sennheiser", unit: "Bộ" },
    { name: "Micro Rode NTG2", unit: "Bộ" },
    { name: "Micro Shotgun - Boya-BM6060", unit: "Bộ" },
    { name: "Micro Shotgun - Synco D1", unit: "Bộ" },
    { name: "Bộ Inear Sennheiser", unit: "Bộ" },
    { name: "Bộ Mono DI-Box", unit: "Bộ" },
    { name: "Bộ Stereo DI-Box", unit: "Bộ" },
    { name: "Bộ Recorder Zoom F8", unit: "Bộ" },
    { name: "Bộ Recorder Zoom H6", unit: "Bộ" },
    { name: "Box Midas 16", unit: "Bộ" },
    { name: "Box Chia Tín Hiệu", unit: "Bộ" },
    { name: "Bộ XLR To Optical - 2in/2out", unit: "Bộ" },
    { name: "Bộ XLR To Optical - 4in/4out", unit: "Bộ" },
    { name: "Bộ XLR To Optical - 8in/8out", unit: "Bộ" },
    { name: "Tai Nghe Kiểm Âm + Jack 6mm To XLR", unit: "Bộ" },
    { name: "Bộ Shure MC - Sony", unit: "Bộ" },
    { name: "Cross Xilica XP 4080", unit: "Bộ" },
    { name: "Cross Admax", unit: "Bộ" },
    { name: "Coross Asly", unit: "Bộ" },
    { name: "Bộ Lá Sóng Sennheiser", unit: "Bộ" },
    { name: "Wireless Boom - Sennheiser", unit: "Bộ" },
    { name: "Rdnet Control", unit: "Bộ" },
    { name: "Lông Thú Chắn Gió", unit: "Bộ" },
    { name: "Bộ Đàm Motorola - Âm Thanh", unit: "Bộ" },
    { name: "Balang Treo Loa", unit: "Bộ" },
    { name: "Giá Treo Loa - RCF", unit: "Bộ" },
    { name: "Dây Tín Hiệu Canon", unit: "Sợi" },
    { name: "Dây Mạng CAT6", unit: "Sợi" },
    { name: "Dây Nguồn Điện - Âm Thanh", unit: "Sợi" },
    { name: "Tủ Điện 100A - Âm Thanh", unit: "Tủ" },
    { name: "Chân Loa", unit: "Chân" },
    { name: "Chân Organ", unit: "Chân" },
    { name: "Chân Guitar", unit: "Chân" },
    { name: "Chân Mic - Tam Giác", unit: "Chân" },
    { name: "Chân Mic - Tròn", unit: "Chân" },
    { name: "Chân Mic - Để BànTranshine HY-332", unit: "Chân" },
    { name: "Imax 27''", unit: "Máy" },
    { name: "Mac Pro 15''", unit: "Máy" },
    { name: "Mac Pro 13''", unit: "Máy" },
    { name: "Mac Air 13''", unit: "Máy" },
    { name: "HDD", unit: "HDD" },
    { name: "Trạm Điện Di Động", unit: "Bộ" },
    { name: "Ổ Cắm Điện 10 Lỗ", unit: "Ổ" },
    { name: "Ổ Cắm Điện 6 Lỗ", unit: "Ổ" },
    { name: "Bộ Sạc Pin AA", unit: "Bộ" },
    { name: "Bộ Sạc Pin AA - Nhỏ", unit: "Bộ" },
    { name: "Pin AA", unit: "Pin" },
    { name: "UPS 1K - Âm Thanh", unit: "UPS" },
  ],
  "ANH TÌNH": [
    { name: "Mixer MA 2 SCREEN", unit: "Bộ" },
    { name: "Mixer Tiger Touch", unit: "Bộ" },
    { name: "Mixer Pear 2010", unit: "Bộ" },
    { name: "Đèn Spot PR - 1000w", unit: "Bộ" },
    { name: "Đèn Spot LED - 400w", unit: "Bộ" },
    { name: "Đèn BigEye", unit: "Bộ" },
    { name: "Đèn Katana - 1M", unit: "Bộ" },
    { name: "Đèn Katana - 50CM", unit: "Bộ" },
    { name: "Đèn Beam 260", unit: "Bộ" },
    { name: "Đèn Beam 230", unit: "Bộ" },
    { name: "Đèn Beam 190 - LED", unit: "Bộ" },
    { name: "Đèn Parled 2in1 - 3K2 + 5K6", unit: "Bộ" },
    { name: "Đèn Parled BK - Outdoor", unit: "Bộ" },
    { name: "Đèn Parled - Indoor", unit: "Bộ" },
    { name: "Đèn Cyclorama LED", unit: "Bộ" },
    { name: "Đèn Fresnel 200W - LED", unit: "Bộ" },
    { name: "Đèn Fresnel 2000W - Xanh", unit: "Bộ" },
    { name: "Đèn Led COB 200W", unit: "Bộ" },
    { name: "Đèn Blinder 750W", unit: "Bộ" },
    { name: "Đèn Par 64 - 1000W", unit: "Bộ" },
    { name: "Đèn Profile 2000W", unit: "Bộ" },
    { name: "Đèn Profile 750W", unit: "Bộ" },
    { name: "Đèn Profile 2000W - LED", unit: "Bộ" },
    { name: "Đèn Profile 300W - LED", unit: "Bộ" },
    { name: "Đèn Follow DTS - 1500W", unit: "Bộ" },
    { name: "Đèn Laser 5W", unit: "Bộ" },
    { name: "Máy Haze Z500", unit: "Bộ" },
    { name: "Máy Haze Z6500", unit: "Bộ" },
    { name: "Máy Khói Z3000W", unit: "Bộ" },
    { name: "Tăng Cường Tín Hiệu Ánh Sáng", unit: "Bộ" },
    { name: "CS Dimmer Pack - 12CB", unit: "Bộ" },
    { name: "Bộ Art Net - 16 Out", unit: "Bộ" },
    { name: "Khung Truss Nhôm - 400x400", unit: "Mét" },
    { name: "Khung Truss Nhôm - Tròn 4m2", unit: "Bộ" },
    { name: "Khung Truss Sắt - 400x400", unit: "Mét" },
    { name: "Khung Truss Sắt - Tròn 6m", unit: "Bộ" },
    { name: "Khung Truss Sắt - Tròn 2m", unit: "Bộ" },
    { name: "Tuýp Đèn Beam", unit: "Cây" },
    { name: "Cùm Đèn", unit: "Cùm" },
    { name: "Palang - 2T", unit: "Bộ" },
    { name: "Dây Bẹ - 5T", unit: "Bộ" },
    { name: "Chân Chỏi Truss", unit: "Chân" },
    { name: "Tủ Điện 250A", unit: "Bộ" },
    { name: "Dây Điện - 3 Pha", unit: "Mét" },
    { name: "Dây Điện - 16 Lõi", unit: "Dây" },
    { name: "Dây Điện - Đấu Nối", unit: "Dây" },
    { name: "Dây Tín Hiệu Dài - Ánh Sáng", unit: "Dây" },
    { name: "Dây Tín Hiệu Ngắn - Ánh Sáng", unit: "Dây" },
    { name: "Tấm Palet Nhựa", unit: "Tấm" },
  ],
  "ALTA": [
    { name: "LED P3.91 - Indoor - Cabin 500x500", unit: "Cabin" },
    { name: "Magnimage - MH570", unit: "Bộ" },
    { name: "Cardsen Nova  MCTRL600", unit: "Bộ" },
    { name: "Bộ PC + Card SDI + Màn Hình PC", unit: "Bộ" },
    { name: "Dây DVI - LED", unit: "Dây" },
    { name: "Dây Mạng CAT6 - 50M", unit: "Dây" },
    { name: "Dây Tín Hiệu Line - RJ45", unit: "Dây" },
    { name: "Dây Nguồn Line - LED", unit: "Dây" },
    { name: "Dây Nguồn 16A - LED", unit: "Dây" },
    { name: "Hộp Điện 20A - LED", unit: "Hộp" },
    { name: "Dây Điện - 3 Pha 63A", unit: "Dây" },
    { name: "Tay Chỏi LED", unit: "Tay" },
    { name: "Tuýt Sắt LED", unit: "Tuýt" },
    { name: "Đế Sắt LED - 20cmx30cm", unit: "Đế" },
    { name: "Đà LED - Sắt Hộp", unit: "Cây" },
  ],
  "DMX": [
    { name: "Matrix Led - Thanh 1M", unit: "Thanh" },
    { name: "Matrix Led - Dây", unit: "Mét" },
    { name: "Matrix Led - Tube 1M", unit: "Thanh" },
    { name: "Matrix Led - Vuông 60x60", unit: "Bộ" },
    { name: "Key 3 - Control Matrix", unit: "Cái" },
    { name: "Nguồn 12V - Matrix Led", unit: "Bộ" },
    { name: "Laptop MSI", unit: "Bộ" },
    { name: "Laptop Alienware", unit: "Bộ" },
    { name: "Dây Mạng CAT6", unit: "Dây" },
    { name: "Dây Nguồn Điện", unit: "Dây" },
    { name: "Tủ Điện 100A", unit: "Bộ" },
  ],
  "LỮ NHẠC": [
    { name: "Máy Hàn Lớn", unit: "Cái" },
    { name: "Máy Hàn Nhỏ", unit: "Cái" },
    { name: "Máy Cắt Lớn", unit: "Cái" },
    { name: "Máy Hơi Lớn", unit: "Cái" },
    { name: "Máy Hơi - 30L Tratek", unit: "Cái" },
    { name: "Máy Phay 6F - Makita", unit: "Cái" },
    { name: "Máy Khoan 13 - Bosch", unit: "Cái" },
    { name: "Máy Cưa Gỗ - Bosch - Cầm Tay", unit: "Cái" },
    { name: "Máy Mài 1T - Makita", unit: "Cái" },
    { name: "Máy Mài 1T5 - Makita", unit: "Cái" },
    { name: "Máy Mài 1T5 - Makita 9553B", unit: "Cái" },
    { name: "Máy Cưa Đĩa - Bosch 190", unit: "Cái" },
    { name: "Máy Khoan - 750W", unit: "Cái" },
    { name: "Máy Khoan - Bosch 750W", unit: "Cái" },
    { name: "Máy Khò - Talon", unit: "Cái" },
    { name: "Máy Cưa Lọng", unit: "Cái" },
    { name: "Máy Bắn Đinh - F50", unit: "Cái" },
    { name: "Máy Chà Nhám - FEG", unit: "Cái" },
    { name: "Súng Bắn Đinh", unit: "Cái" },
    { name: "Súng Bắn Đinh - Bê Tông", unit: "Cái" },
    { name: "Máy Khoan Hukan - 2Pin + 1 Sạc - Dòng 30", unit: "Cái" },
    { name: "Máy Khoan Hukan - 2Pin + 1 Sạc - Dòng 31", unit: "Cái" },
    { name: "Máy Khoan Cầm Tay - Dòng 33", unit: "Cái" },
    { name: "Máy Cưa Gỗ - (Bosch Sang Makita)", unit: "Cái" },
    { name: "Súng Bắn Đinh - Dòng 37", unit: "Cái" },
    { name: "Máy Hút Bụi", unit: "Cái" },
    { name: "Bộ Nguồn 12V - 50A - Sân Khấu", unit: "Cái" },
    { name: "Kính Cường Lực 12mm - NEW", unit: "Cái" },
    { name: "Kính Cường Lực 12mm - Cho Thuê", unit: "Cái" },
    { name: "Ván MDF - NEW", unit: "Cái" },
    { name: "Ván MDF - Cho Thuê", unit: "Cái" },
    { name: "Decal - Màu Cơ Bản", unit: "Cái" },
    { name: "Decal In Artwork", unit: "Cái" },
    { name: "Decal In Artwork ( Xuyên Đèn )", unit: "Cái" },
    { name: "Decal In + Bế Artwork ( Xuyên Đèn )", unit: "Mét" },
    { name: "Mặt Dựng : Khung Sắt + Ván + Sơn", unit: "Cái" },
    { name: "Mặt Dựng : Khung Sắt + Mica Trong + Led 7 Màu", unit: "Cái" },
    { name: "Mặt Dựng : Khung Sắt Để Gắn LED", unit: "Cái" },
    { name: "Khung Sắt Vuông 30 x 30 - Thẳng + Làm Mới", unit: "Cái" },
    { name: "Khung Sắt Vuông 30 x 30 - Thẳng + Cho Thuê", unit: "Cái" },
    { name: "Khung Sắt Vuông 30 x 30 - Cong - Quá Khổ + Làm Mới", unit: "Cái" },
    { name: "Khung Sắt Vuông 30 x 30 - Cong - Quá Khổ + Cho Thuê", unit: "Cái" },
    { name: "Khung Sắt + Hiflex", unit: "Mét" },
    { name: "Khung Sắt + Formex + In PP ( 1 Mặt )", unit: "Mét" },
    { name: "Khung Sắt + Formex + In PP ( 2 Mặt )", unit: "Mét" },
    { name: "Khung Sắt + Ván Sơn Màu", unit: "Cái" },
    { name: "Hộp Đèn 10cm : Khung Sắt + Mica + Nguồn + Dây LED", unit: "Sợi" },
    { name: "Hộp Đèn 20cm : Khung Sắt + Mica + Nguồn + Dây LED", unit: "Mét" },
    { name: "Hộp Đèn 30cm : Khung Sắt + Mica + Nguồn + Dây LED", unit: "Cặp" },
    { name: "Layer Truss + Gia Cố", unit: "M3" },
  ],
};

export const NCC_LIST = Object.keys(NCC_CATALOG);

// Bộ phận được phép xem/thuê từng NCC
export const NCC_DEPT = {
  'NIPI':       'TECH',   // KỸ THUẬT-ORDER
  'LONG PATE':  'ATAS',   // BỘ PHẬN ORDER - ATAS
  'ANH TÌNH':   'ATAS',
  'ALTA':       'ATAS',
  'DMX':        'ATAS',
  'LỮ NHẠC':   'STAGE',  // BỘ PHẬN ORDER - SÂN KHẤU
};
